name = "DICOMUtils"
uuid = "d427e4c1-f2bb-45be-a498-7217d8b6de98"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
